version: "3.9"
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: appsecret
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    build:
      context: ./server
    environment:
      - DATABASE_URL=postgresql://appuser:appsecret@db:5432/appdb?schema=public
      - PORT=4000
      - NODE_ENV=production
    depends_on:
      - db
    ports:
      - "4000:4000"

  client:
    build:
      context: ./client
    environment:
      - VITE_API_URL=http://localhost:4000
    ports:
      - "8080:80"
    depends_on:
      - server

volumes:
  pgdata:
